# Makefile generated by OpenModelica

# Simulations use -O3 by default
SIM_OR_DYNLOAD_OPT_LEVEL=-O3
CC=g++
CXX=g++
LINK=g++ -shared -export-dynamic
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE= 
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) -I"/usr/include/omc" ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -march=native -mfpmath=sse ${MODELICAUSERCFLAGS} 
LDFLAGS=-L"/usr/lib/omc" -lc_runtime
SENDDATALIBS= -lsendData -lQtNetwork -lQtCore -lQtGui -lrt -lpthread
PERL=perl
MAINFILE=Test.cpp

.PHONY: Test
Test: $(MAINFILE) Test_functions.cpp Test_functions.h Test_records.c
	 $(CXX) -I. -o Test$(EXEEXT) $(MAINFILE)    -lsim -linteractive $(CFLAGS) $(SENDDATALIBS) $(LDFLAGS) -Wl,-Bstatic -lf2c -Wl,-Bdynamic Test_records.c
Test.conv.cpp: Test.cpp
	 $(PERL) /usr/share/omc/scripts/convert_lines.pl $< $@.tmp
	 @mv $@.tmp $@